output:
  sort-results: true # sorts by filepath, line and column

linter-settings:
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed by logutils.Log
      # logrus is only allowed in logutils pkg
      - github.com/sirupsen/logrus
    package-with-error-message: "logrus only allowed in logutils package"
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/org/project
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  lll:
    line-length: 120 # open to changes, set to default
  misspell:
    locale: US


linters:
  disable-all: true
  enable:
    - depguard
    - funlen
    #- gocritic
    - goimports
    - gomnd
    - lll
    - misspell

  # don't enable:
  # - asciicheck
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - revive
  # - wsl

#issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  #exclude-rules:
  #- path: _test\.go
