name: linter
on:
  push:
    branches:
      - main
      - dev
jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - name: fetch repo
        uses: actions/checkout@v2
      - name: run linter
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--tests=false"
