###################################
###################################
#                                 #
#     GREETINGS GITHUB ACTION     #
#                                 #
###################################
###################################

# simple workflow to greet first time
# contributors, whether they open a PR
# or an Issue

name: "Greetings"

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Congrats! You've opened your first issue. Please refer to the contributing docs if you have any questions. Or find us in Slack"
          pr-message: "Congrats! You've opened your first pull request. Please refer to the contributing docs if you have any questions. Or find us in Slack"
